### ISSUE TITLE
Why "DO NOT run the dkms_setup.bash script"

### ISSUE THREAD

**Issue by Bouni** [jeonghanlee/CCAT-env#2]
Can you please give me some insight why I should not "run the dkms_setup.bash script" if I want to "setup IgH EtherCAT Master via https://github.com/icshwi/etherlabmaster"?

I did all the steps up to https://github.com/jeonghanlee/CCAT-env#notice, and the modules show up but after a reboot they are not loaded ...

**Comment by Bouni** [comment]
That's strange, I tried to do a `make dkms_install` again and it gave me an error that I'm missing some kernel headers. So I did a `sudo apt install linux-headers-4.19.0-23-rt-amd64` (that's the headers mentioned by the error) and a `make dkms_install` afterwards

That gave me 
```
sudo /usr/sbin/dkms install -m ccat -v bc9e28f
Module ccat/bc9e28f already installed on kernel 4.19.0-23-rt-amd64/x86_64
```
So once more I did `make setup`

which gave me the expected output:

```
ccat
ccat_netdev
ccat_gpio
ccat_sram
ccat_systemtime
ccat_update
rmmod ccat_update
rmmod ccat_systemtime
rmmod ccat_sram
rmmod ccat
rmmod ccat_gpio
rmmod ccat_netdev
insmod /lib/modules/4.19.0-23-rt-amd64/updates/dkms/ccat.ko
insmod /lib/modules/4.19.0-23-rt-amd64/updates/dkms/ccat_netdev.ko
insmod /lib/modules/4.19.0-23-rt-amd64/updates/dkms/ccat_gpio.ko
insmod /lib/modules/4.19.0-23-rt-amd64/updates/dkms/ccat_sram.ko
insmod /lib/modules/4.19.0-23-rt-amd64/updates/dkms/ccat_systemtime.ko
insmod /lib/modules/4.19.0-23-rt-amd64/updates/dkms/ccat_update.ko


It is OK to see "RULES_DKMS: recipe for target 'setup' failed"
---------------------------------------------------------------------
crw------- 1 root root 244, 0 Apr 19 07:08 /dev/ccat_sram0
crw------- 1 root root 243, 0 Apr 19 07:08 /dev/ccat_update0
---------------------------------------------------------------------
```

After a reboot the modules are loaded automatically. 

```
lsmod | grep ccat
ccat_update            16384  0
ccat_systemtime        16384  0
ccat_sram              16384  0
ccat_netdev            20480  0
ccat_gpio              16384  0
ccat                   16384  2 ccat_sram,ccat_update
mfd_core               16384  2 ccat,lpc_ich
```

Did I miss something?

**Comment by jeonghanlee** [comment]
These repos do not reflect the latest kernel configuration, so I would like to emphasize what you see here could be out-of-date information.

If you want to use https://github.com/icshwi/etherlabmaster, they have their own dkms configuration, so you don't need the ccat dkms configuration. 

What I remember is
1. ccat setup first
2. ethercatmaster setup later with Beckhoff ccat kernel patch

Please check README and find the ccat section at https://github.com/icshwi/etherlabmaster

It was very tricky since they share the same kernel module names. So please look carefully at what can be loaded, and how it works within kernel spaces.

**Comment by Bouni** [comment]
I got it working!

icshwi/etherlabmaster explicitly recommends to use your repo in order to get CCAT working ([link](https://github.com/icshwi/etherlabmaster#beckhoff-ccat-fpga-kernel-mode-driver-1))

I work on a blog post which I'll link here once everything is setup so that others have kind of a guide.

As you said, all this can be very tricky ...

**Comment by jeonghanlee** [comment]
This is the way! Thank you for sharing your result. I will close this issue.
